version: '3.7'
services:

  # mysql:
  #   image: mariadb/server

  #   container_name: mysql_db

  #   environment:
  #     - MARIADB_ROOT_PASSWORD=mypassword
  #     - MARIADB_DATABASE=testing_db
  #     - MARIADB_USER=bruno
  #     - MARIADB_PASSWORD=password

  service:
    build:
      context: .

    container_name: service

    # ports:
    #   - "4040:4040"

    volumes:
      - type: bind
        source: ./service/
        target: /root/service/

  spark-master:
    build:
      context: .

    container_name: spark-master

    hostname: spark-master

    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
      - "3306:3306"

    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "PYSPARK_PYTHON=/usr/bin/python3"

    volumes:
      - type: bind
        source: ./service/
        target: /root/service/

    entrypoint: "bash /start_master.sh"

  spark-worker:
    build:
      context: .

    container_name: spark-worker

    depends_on:
      - spark-master

    ports:
      - "8081:8081"

    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "PYSPARK_PYTHON=/usr/bin/python3"

    volumes:
      - type: bind
        source: ./service/
        target: /root/service/

    entrypoint: "bash /start_worker.sh"
