version: '3.7'
services:

  scala:
    build:
      context: .

    volumes:
      - type: bind
        source: ./scala_project
        target: /root/home

    # docker-compose run scala sh

  mysql:
    image: mariadb/server
    environment:
      - MARIADB_ROOT_PASSWORD=mypassword
      - MARIADB_DATABASE=testing_db
      - MARIADB_USER=bruno
      - MARIADB_PASSWORD=password

    volumes:
      - type: bind
        source: ./mysql_config
        target: /etc/mysql/conf.d

    # SHOW BINARY LOGS;


  spark-master:
    build:
      context: ./spark/

    container_name: spark-master

    hostname: spark-master

    ports:
      - "8080:8080"
      - "7077:7077"

    networks:
      - spark_network

    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"

    entrypoint: "bash /start_master.sh"


  spark-worker:
    build:
      context: ./spark/

    depends_on:
      - spark-master

    ports:
      - 8080

    networks:
      - spark_network

    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"

    entrypoint: "bash /start_worker.sh"

  
networks:
  spark_network:
    driver: bridge
    ipam:
      driver: default