version: '3.7'
services:

  spark-master:
    build:
      context: ./spark/

    container_name: spark-master

    hostname: spark-master

    ports:
      - "8080:8080"
      - "7077:7077"

    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"

    entrypoint: "bash /start_master.sh"

  spark-worker:
    build:
      context: ./spark/

    depends_on:
      - spark-master

    ports:
      - "8081:8081"

    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"

    entrypoint: "bash /start_worker.sh"
